### ISSUE TITLE
Failed to load the TerosHDL package

### ISSUE THREAD

**Issue by Lucifer-02** [TerosTechnology/terosHDL#83]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Linux Mint
**Thrown From**: [TerosHDL](https://github.com/TerosTechnology/terosHDL) package 1.1.9

### Stack Trace

Failed to load the TerosHDL package

```
At Cannot find module './run/simulator/main'
Require stack:
- /home/lucifer/.atom/packages/TerosHDL/lib/main.js
- /usr/share/atom/resources/app.asar/static/index.html

Error: Cannot find module './run/simulator/main'
Require stack:
- /home/lucifer/.atom/packages/TerosHDL/lib/main.js
- /usr/share/atom/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at /packages/TerosHDL/lib/main.js:24:53)
    at /packages/TerosHDL/lib/main.js:358:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:756277)
    at requireModule (/usr/share/atom/resources/app/static/<embedded>:14:1191586)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3400508)
    at /usr/share/atom/resources/app/static/<embedded>:11:3387048
    at Package.measure (/usr/share/atom/resources/app/static/<embedded>:11:3385848)
    at Package.load (/usr/share/atom/resources/app/static/<embedded>:11:3386621)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/static/<embedded>:11:384071)
    at PackageManager.loadPackage (/usr/share/atom/resources/app/static/<embedded>:11:382799)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:385371)
    at /usr/share/atom/resources/app/static/<embedded>:11:914488
    at r (/usr/share/atom/resources/app/static/<embedded>:11:909094)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1190909)
    at /usr/share/atom/resources/app/static/<embedded>:14:1191063
    at Socket.<anonymous> (/usr/share/atom/resources/app/static/<embedded>:14:1189665)
    at Socket.emit (events.js:228:7)
    at Pipe.<anonymous> (net.js:664:12)
```

### Commands

```
```

### Non-Core Packages

```
TerosHDL 1.1.9 
```

**Comment by qarlosalberto** [comment]
I recommend using the VSCode version. We have stopped the development for Atom. You will find a lot of new features :)

https://marketplace.visualstudio.com/items?itemName=teros-technology.teroshdl
https://terostechnology.github.io/terosHDLdoc/
